---

- name: Add OpenLDAP system user to additional groups
  user:
    name: 'openldap'
    groups: '{{ slapd_append_groups | join(",") | default(omit) }}'
    append: True
    state: 'present'
  notify: [ 'Restart slapd' ]
  when: slapd_pki is defined and slapd_pki

- name: Execute all handlers if needed
  meta: flush_handlers
  when: slapd_pki is defined and slapd_pki

- name: Configure TLS certificates
  ldap_attr:
    dn: 'cn=config'
    name: '{{ item.key }}'
    values: '{{ item.value }}'
    state: 'exact'
  with_dict:
    olcTLSCACertificateFile:  '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_ca }}'
    olcTLSCertificateFile:    '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_crt }}'
    olcTLSCertificateKeyFile: '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_key }}'
    olcTLSDHParamFile:        '{{ slapd_pki_path + "/" + slapd_pki_realm + "/" + slapd_pki_dhparam }}'
    olcTLSCipherSuite:        '{{ slapd_pki_ciphers }}'
  when: slapd_pki is defined and slapd_pki

